name: Continuous Integration

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./Matomo.Maui

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./Matomo.Maui
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Restore packages for solution
        run: dotnet restore

      - name: Build
        run: dotnet build